### ISSUE TITLE
clothing1M

### ISSUE THREAD

**Issue by xjtushujun** [Newbeeer/L_DMI#1]
Can you provide the following files: noisy_train.txt,clean_val.txt,clean_test.txt.
        if train==True:
            flist = os.path.join(root, "annotations/noisy_train.txt")
        if valid==True:
            flist = os.path.join(root, "annotations/clean_val.txt")
        if test==True:
            flist = os.path.join(root, "annotations/clean_test.txt")

**Comment by Newbeeer** [comment]
Hi, sorry for the late response. I have uploaded these files. BTW do you have the image data for Clothing1M? If not I can upload it on another website.

**Comment by xjtushujun** [comment]
Thanks, I have download the original data. However, the name of the .txt files in the original data is different from yours. Why?

**Comment by Newbeeer** [comment]
We preprocess three original files (clean_train_key_list.txt, clean_val_key_list.txt, noisy_train_key_list.txt). The indices in the original file are consistent with the image path in the current .txt files. We combine the original indices files and label files into one .txt file.

**Comment by guixianjin** [comment]
Hi! It seems that there is a small typo in file clean_train.txt: 
line 10620:  images/2/26/3761328114,905362226.jpg  don't follow the corresponding label.
