### ISSUE TITLE
It seems that this new loss can also be used for clean data?

### ISSUE THREAD

**Issue by guixianjin** [Newbeeer/L_DMI#10]
A wonderful work! It seems that this new loss can also be used for clean data? And different from cross entropy loss, which just calculates loss for each example separately, this loss consider the class distribution information between examples. Maybe it can achieve better performance. Have you tried it ? @CsPsy @Newbeeer

**Comment by Newbeeer** [comment]
I haven't try that due to the L_dmi need warm start-up, i.e., pretaining, due to exploded gradient. Please refer to [https://github.com/Newbeeer/L_DMI/issues/11](https://github.com/Newbeeer/L_DMI/issues/11) for the reason.
