### ISSUE TITLE
DMI_loss

### ISSUE THREAD

**Issue by FengJiang001** [Newbeeer/L_DMI#13]
Hello, I am trying to implement DMI_loss, where can I get the data set of dogcat and clothing?

Thank you!

**Comment by Newbeeer** [comment]
Hi,

The dogcat dataset can be found at [https://www.kaggle.com/c/dogs-vs-cats](https://www.kaggle.com/c/dogs-vs-cats) .

The clothing1M dataset can be found at [https://drive.google.com/folderview?id=0B67_d0rLRTQYU2E4aHNHaE1uMTg&usp=sharing](https://drive.google.com/folderview?id=0B67_d0rLRTQYU2E4aHNHaE1uMTg&usp=sharing)

Detailed instructions and terms of use are listed in their README.md. Please do not redistribute the dataset ( said by the original data collector). Thanks.

**Comment by Newbeeer** [comment]
Moreover, we have split the data into clean_test.txt, clean_train. txt,clean_val.txt and noisy_train.txt in the clothing directory.
