### ISSUE TITLE
您好，如何才能具有访问链接的权限？

### ISSUE THREAD

**Issue by whyandbecause** [Newbeeer/L_DMI#16]
Thanks very much for your interest. Please find the dataset at the following URL:

https://drive.google.com/folderview?id=0B67_d0rLRTQYU2E4aHNHaE1uMTg&usp=sharing

Detailed instructions and terms of use are listed in the README.md. Please do not redistribute the dataset ( said by the original data collector). Thanks.

_Originally posted by @Newbeeer in https://github.com/Newbeeer/L_DMI/issues/8#issuecomment-562639396_

**Comment by Newbeeer** [comment]
I can still access the google drive link.

**Comment by limengting-evelyn** [comment]
> I can still access the google drive link.

您好，链接打开后显示我需要访问权限，我已经申请但没有得到回复，请问如何得到访问权限？

**Comment by limengting-evelyn** [comment]
> I can still access the google drive link.

The link says I need access. I have applied for access but not gotten a reply. May i ask how I can get an access?

**Comment by Newbeeer** [comment]
Could you try this url : https://drive.google.com/drive/folders/0B67_d0rLRTQYU2E4aHNHaE1uMTg?resourcekey=0-_FShcGYZwIyESjnz6S6aLQ&usp=sharing 

I'm not the owner of the google drive folder. I've asked the owner to share It, but not sure whether the owner would response.

**Comment by limengting-evelyn** [comment]
> Could you try this url : https://drive.google.com/drive/folders/0B67_d0rLRTQYU2E4aHNHaE1uMTg?resourcekey=0-_FShcGYZwIyESjnz6S6aLQ&usp=sharing
> 
> I'm not the owner of the google drive folder. I've asked the owner to share It, but not sure whether the owner would response.

This url works, thanks a lot!!!
