### ISSUE TITLE
For Clothing1M dataset, how many GPU memory are needed?

### ISSUE THREAD

**Issue by guixianjin** [Newbeeer/L_DMI#3]
Hi! I try to run the code for Clothing1M. But error report: GPU memory is not enough. I use RTX 2080Ti, about 10G GPU memory. So, I want to know if it's the GPU‘ memory too small.

**Comment by Newbeeer** [comment]
Hi! We use 6 GPU during training (batch size=256), with 12G memory on each GPU.

**Comment by guixianjin** [comment]
OKay. Very thanks!
