### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by Faldict** [Newbeeer/L_DMI#5]
Hi,

Your code looks good! But why do you set confusion matrix rather simple? I don't think your noisy data is really noisy. Have you tried more sophisticated cases?

https://github.com/Newbeeer/L_DMI/blob/4376ede8d9208db9202f1483244ee0b6ee31a0c7/CIFAR-10/dataset.py#L37

**Comment by Newbeeer** [comment]
Hi,

Very sorry for the huge delay. I have add the class-independent noise-type to this repo and the original paper. Please refer to our camera-ready version [https://newbeeer.github.io/newbeeer.github.io/assets/files/dmi.pdf](https://newbeeer.github.io/newbeeer.github.io/assets/files/dmi.pdf), where we include both the class-dependent noise (in the Sec 5.2) and the class-independent noise (in Appendiex D).

If you are interested in any other specific cases, please let me know. I am glad to have a try.

Thanks!

Best,
Yilun
