### ISSUE TITLE
det() always equals 0 when the number of categories is much larger than batch size, e.g., 700 classes v.s. 64 batch.

### ISSUE THREAD

**Issue by liu-xb** [Newbeeer/L_DMI#7]
A great work! 

However, when the number of categories is much larger than batch size, e.g., 700 categories v.s. batch size being 64, det() always equals 0. I use ResNet50 as backbone. The batch size is limited by memory.

**Comment by Newbeeer** [comment]
Hi,

Very sorry for the huge delay. In your batch-size=64 cases, some categories would be absense in the batch since 700>64. In this case, some column in the joint prob matrix would be zero. Hence, the matrix would be low rank in your cases, leadning to det(mat)=0. 

Best,
Yilun
