### ISSUE TITLE
Clothing1M数据集下载

### ISSUE THREAD

**Issue by tianchenweikai** [Newbeeer/L_DMI#8]
你好，我希望能尝试Clothing1M数据集，请问一下我在哪里可以下载该数据集吗？

**Comment by Newbeeer** [comment]
Thanks very much for your interest. Please find the dataset at the following URL:

https://drive.google.com/folderview?id=0B67_d0rLRTQYU2E4aHNHaE1uMTg&usp=sharing

Detailed instructions and terms of use are listed in the README.md. Please do not redistribute the dataset ( said by the original data collector). Thanks.

**Comment by Newbeeer** [comment]
Moreover, we have split the data into clean_test.txt, clean_train. txt,clean_val.txt and noisy_train.txt in the clothing directory.

**Comment by tianchenweikai** [comment]
OK，I have download it. Thank you very much.
